# Generated by Django 3.2.16 on 2023-02-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
        ('venta_detalles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venta_Detalles',
            new_name='VentaDetalles',
        ),
    ]
