# Generated by Django 3.2.16 on 2023-02-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='idUsuario',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
