# Generated by Django 3.2.16 on 2023-02-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20230210_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='nombre@gmail.com', max_length=100),
        ),
    ]
